# Generated by Django 3.1.6 on 2021-02-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_comments_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='country',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
