# Generated by Django 3.1.6 on 2021-02-25 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20210224_1059'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ratings',
            new_name='Rate',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='rating',
            new_name='rate',
        ),
    ]
